[workspace]
members = [
]
[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[[bin]]
name = "oxidate_out"
path = "src/main.rs"
[dependencies]
libc= "0.2"
